export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const REQUEST_STARTED ="REQUEST_STARTED";
export const REQUEST_SUCCEEDED = "REQUEST_SUCCEEDED"; 
export const REQUEST_FAILED =  "REQUEST_FAILED";

export const FETCH_ALERTS_BEGIN = "FETCH_ALERTS_BEGIN";
export const FETCH_ALERTS_SUCCESS = "FETCH_ALERTS_SUCCESS";
export const FETCH_ALERTS_FAILURE = "FETCH_ALERTS_FAILURE"


